services:
  # 1. База данных
  db:
    image: postgres:15-alpine
    container_name: analysis_db
    environment:
      POSTGRES_DB: analysis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Брокер сообщений
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: analysis_rabbit
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8082:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/analysis_db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      JWT_SECRET: a-string-secret-at-least-256-bits-long
      JWT_EXPIRATION: 86400000
    depends_on:
      - db

  # 3. Java Input Service
  input-service:
    build:
      context: ./input
      dockerfile: Dockerfile
    container_name: input_service
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/analysis_db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      JWT_SECRET: a-string-secret-at-least-256-bits-long
    depends_on:
      - auth-service
      - db
      - rabbitmq

  # 4. Java Output Service
  output-service:
    build:
      context: ./output
      dockerfile: Dockerfile
    container_name: output_service
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/analysis_db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      JWT_SECRET: a-string-secret-at-least-256-bits-long
    depends_on:
      - input-service
      - db
      - rabbitmq

  # 5. Python Math Service
  python-service:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_service
    environment:
      RABBITMQ_HOST: rabbitmq
      DB_URL: postgresql://postgres:root@db:5432/analysis_db
      PYTHONUNBUFFERED: 1
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
  rabbit_data: